### PR TITLE
add stub implementation of extract_noattr for other platforms

### PR DESCRIPTION
**Pull request by sunshowers**
This allows xattr to at least compile on platforms like illumos, even though it isn't currently supported there.

### CODE REVIEW

**Comment by Stebalien** [comment]
Does enabling the "unsupported" feature not work for you?

**Comment by sunshowers** [comment]
Hmm, I'm using xattr as a transitive dependency of the tar package.

**Comment by sunshowers** [comment]
Looks like the unsupported feature is enabled by default, yet `cargo build` without arguments fails on illumos. Maybe the support for unsupported platforms broke at some point?

**Comment by josh-sanders** [comment]
Thank you sunshowers, this is great. It works on OmniOS.

**Comment by Stebalien** [comment]
Ah... I see.

**Comment by Stebalien** [comment]
This should now be fixed on the latest release.

**Comment by sunshowers** [comment]
Thanks! Your solution (https://github.com/Stebalien/xattr/commit/2352bdc50f5f2e5fafb3afee67c06f793d31eb85) looks great.

**Pull request closed without merging**
