### PR TITLE
Add GNU/Hurd support

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by Stebalien** [comment]
Just to check, you've run the tests on GNU/Hurd? Any idea how this could be tested in CI?

**Comment by sthibaul** [comment]
I haven't actually tested because various patches are still pending releasing & versions being bumped, so it's not easy to test. But the interface is really just the glibc interface, so if the code works on Linux it should work just fine on the Hurd, if it doesn't it's a bug in the Hurd, not in rust-xattr..

**Comment by Stebalien** [comment]
Possibly, I'm not going to merge an untested feature. I'll mark this as draft until everything is ready.

**Comment by sthibaul** [comment]
I have now run the tests. As expected there were unexpected results in corner cases, and as expected it's the glibc implementation that needed to be fixed, I didn't change the rust-xattr implementation.

**Comment by Stebalien** [comment]
I think it would be best to wait for the next glibc release before merging this.

**Comment by sthibaul** [comment]
I don't really see what that would change: it's what is in distributions that actually matters to users.

**Comment by Stebalien** [comment]
Fair enough. Then I guess we can revisit this in a few years...

**Comment by sthibaul** [comment]
? no. This is already pushed to Debian unstable.

**Comment by Stebalien** [comment]
I mean, it's GNU Hurd so not many will care but...

- At the moment, Hurd users will get a nice "unsupported" error and software can check `xattr::SUPPORTED_PLATFORM` to disable extended attributes on unsupported platforms.
- If I just go ahead and merge this, anyone _not_ on Debian unstable will end up with a buggy `xattr` implementation, instead of just a missing one.

What am I missing?

**Comment by sthibaul** [comment]
> At the moment, Hurd users will get a nice "unsupported" error

No, they are getting a build failure:
https://buildd.debian.org/status/fetch.php?pkg=rust-xattr&arch=hurd-i386&ver=1.0.0-1&stamp=1717343472&raw=0

> software can check xattr::SUPPORTED_PLATFORM to disable extended attributes on unsupported platforms

rust-tar doesn't seem to be using it at least.

> If I just go ahead and merge this, anyone not on Debian unstable will end up with a buggy xattr implementation, instead of just a missing one.

Well, sure, but glibc releasing or not does not really change this.

GNU/Hurd distributions are used to cherry-picking such important fixes. Debian unstable now already has it, Guix will follow, there is no other distribution with a Hurd port. I don't see the point of not just merging this already rather than keeping it in the backlog for a not-really-defined time.

**Comment by Stebalien** [comment]
> No, they are getting a build failure:

Not if they're using recent version, or building rust applications from source. But it appears that both actively maintained Hurd distributions (Debian & Guix) are using outdated copies of rust-xattr...

This still rubs me the wrong way, but you're a Hurd author and the harm is... minimal.

**Comment by Stebalien** [comment]
Would you like a release?

**Comment by sthibaul** [comment]
> This still rubs me the wrong way, but you're a Hurd author and the harm is... minimal.

Thanks!

> Would you like a release?

I have already applied the patch to the 1.0.0 version in Debian, so it'll be fine to wait for the next upstream release.

**Pull request merged**
